In [ ]:
---
title: "[Math 421] Assignment 3 by Rodrigue Beleho"
author: "Rodrigue Beleho"
date: "September 19, 2018"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

## Data Manipulation with R

I corrected some data on the Titanic data.

```{r}

titanic = read.csv("C:/Users/student/Desktop/[421] Data/titanic.csv")
library(ggplot2)

```

```{r}
#Changing variables from numerical to categorical
titanic$Survived = factor(titanic$Survived)
titanic$Pclass = factor(titanic$Pclass)
titanic$Sex = factor(titanic$Sex)
```

```{r}
#Question 1

summary(titanic)
sum(is.na(titanic))
```

```{r}
#Question 2
summary(is.na(titanic))
mean_age <- mean(titanic$Age, na.rm = TRUE)
titanic[is.na(titanic$Age),]$Age = mean_age
```




```{r}
#Question 3 and 4
# Removing rows with missing values and columns with unnecessry info
titanic[,1] = NULL
titanic[,"Ticket"] = NULL
titanic[,"Cabin"] = NULL
titanic = na.omit(titanic)

```

```{r}
#Question 5
mean(titanic$Age)
```


```{r}
#Question 6
mean(titanic[titanic$Sex=="female",]$Age)
```
```{r}
#Question 7
median(titanic[titanic$Pclass==1,]$Fare)
```

```{r}
#Question 8
median(titanic[titanic$Sex=="female" & titanic$Pclass!="1",]$Fare)
```

```{r}
#Question 9
median(titanic[titanic$Survived == "1" & titanic$Sex=="female" & titanic$Pclass!="3",]$Age)
```

```{r}
#Question 10
mean(titanic[titanic$Sex == "female" & titanic$Survived == "1" & titanic$Age >= "13" & titanic$Age < "20",]$Fare)
```

```{r}
#Question 11
mean(titanic[titanic$Sex == "female" & titanic$Survived == "1" & titanic$Age >= "13" & titanic$Age < "20" & titanic$Pclass ==1:3, ]$Fare)

```

```{r}
#Question 12

titanic1 <-  titanic[(titanic$Survived=="1")&(titanic$Fare>mean(titanic$Fare)),]
titanic2 <- titanic[(titanic$Survived=="0")&(titanic$Fare>mean(titanic$Fare)),]
nrow(titanic1)/nrow(titanic2)

```

```{r}
#Question 13
titanic$sfare <- (titanic$Fare-mean(titanic$Fare))/sd(titanic$Fare)
```


```{r}
#Question 14
library(ggplot2)
titanic5 <- titanic[titanic$Age<mean(titanic$Age),] 
ggplot(titanic5) + geom_bar(mapping = aes(x = Sex, fill = Survived), position = "dodge")
```

```{r}
#Question 15
titanic3 <- titanic[titanic$Fare>mean(titanic$Fare),]
ggplot(data = titanic3) + geom_density(mapping = aes(x=Age))
```

```{r}
#Question 16
t18=titanic[titanic$Embarked!="",] 
t19=t18[t18$Embarked!="C",] 
ggplot(t19) + geom_density(mapping = aes(x = Age, color = Embarked))
```

```{r}
#Question 17
titanic$cfare[titanic$Fare<mean(titanic$Fare)]= "cheap"
titanic$cfare[titanic$Fare>mean(titanic$Fare)]= "expensive"
```

```{r}
#Question 18

max(titanic$Age)

#The answer is 80
titanic$cage[titanic$Age<=10]="0"
titanic$cage[titanic$Age>10 & titanic$Age<=20]="1"
titanic$cage[titanic$Age>20 &titanic$Age<=30]="2"
titanic$cage[titanic$Age>30 &titanic$Age<=40]="3"
titanic$cage[titanic$Age>40 &titanic$Age<=50]="4"
titanic$cage[titanic$Age>50 &titanic$Age<=60]="5"
titanic$cage[titanic$Age>60 &titanic$Age<=70]="6"
titanic$cage[titanic$Age>70 &titanic$Age<=80]="7"
```

```{r}
#Question 19
titanic19 <- titanic[titanic$cfare=="expensive",] 
ggplot(titanic19) + geom_bar(mapping = aes(x = cage, fill = Survived), position = "dodge")
```

```{r}
#Question 20
ggplot(titanic19) + geom_bar(mapping = aes(x = cage, fill = Survived), position = "dodge")+facet_wrap(~Pclass, nrow=2)